version: '3.8'

services:

  db:
    image: oscarfonts/h2
    container_name: db
    ports:
      - "9092:9092"
    volumes:
      - h2-data:/h2-data
    environment:
      H2_OPTIONS: "-tcp -tcpAllowOthers -tcpPort 9092 -ifNotExists"
    networks:
      - red-mocky

  app:
    image: ipmx0001/itcompose:latest
    container_name: app
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      DB_HOST: db
      DB_PORT: 9092
      DB_NAME: test
      DB_USERNAME: "sa"
      DB_PASSWORD: ""
      PORT: ${APP_PORT}
    networks:
      - red-mocky
    depends_on:
      - db

networks:
  red-mocky:

volumes:
  h2-data:
